"""Generate ``seed/fixtures.json`` and ``seed/seed.sql`` from the source catalog.

``python -m ripplepath.export_fixtures`` regenerates both artifacts. Output is
deterministic (sorted keys, seeded seat counts) so a rebuild produces a
byte-identical file and shows up as an empty diff in git.

The same builder feeds both outputs, which is why the offline fixture and the
Supabase tables cannot silently drift apart.
"""

from __future__ import annotations

import json
from pathlib import Path

from ripplepath.catalog_source import build_catalog
from ripplepath.graph import build_graph, graph_signature
from ripplepath.models import Catalog

SEED_DIR = Path(__file__).resolve().parent.parent / "seed"
FIXTURE_FILE = SEED_DIR / "fixtures.json"
SEED_SQL_FILE = SEED_DIR / "seed.sql"


def _sql_literal(value: object) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, list):
        inner = ", ".join(_sql_literal(v) for v in value)
        return f"ARRAY[{inner}]::text[]"
    escaped = str(value).replace("'", "''")
    return f"'{escaped}'"


def _insert_statements(table: str, columns: list[str], rows: list[dict]) -> list[str]:
    if not rows:
        return []
    lines = [f"-- {table}: {len(rows)} rows", f"INSERT INTO {table}"]
    lines.append("  (" + ", ".join(columns) + ")")
    lines.append("VALUES")
    values = [
        "  (" + ", ".join(_sql_literal(row[col]) for col in columns) + ")" for row in rows
    ]
    lines.append(",\n".join(values) + ";")
    return lines


def render_seed_sql(catalog: Catalog) -> str:
    """Render idempotent INSERT statements for the Supabase tables."""
    sections: list[str] = [
        "-- Ripple seed data (generated by ripplepath.export_fixtures).",
        "-- Do not edit by hand. Regenerate with:",
        "--   python -m ripplepath.export_fixtures",
        "--",
        "-- Course IDs, titles, credits, and prerequisite logic are transcribed by",
        "-- hand from the public Oregon State University 2026-2027 catalog.",
        "-- Term offerings, seat counts, and all student personas are synthetic.",
        "-- See ATTRIBUTION.md for full provenance.",
        "",
        "BEGIN;",
        "",
        "TRUNCATE registration_state, prerequisites, degree_requirements,",
        "         student_states, courses, programs RESTART IDENTITY CASCADE;",
        "",
    ]

    plan: list[tuple[str, list[str], list[dict]]] = [
        (
            "programs",
            [
                "program",
                "institution",
                "label",
                "catalog_year",
                "total_min_credits",
                "source_url",
                "accessed",
            ],
            [p.model_dump() for p in catalog.programs],
        ),
        (
            "courses",
            ["course_id", "title", "credits", "offered_terms", "typical_capacity"],
            [c.model_dump() for c in catalog.courses],
        ),
        (
            "prerequisites",
            ["course_id", "requires_course_id", "relation", "group_id"],
            [p.model_dump() for p in catalog.prerequisites],
        ),
        (
            "degree_requirements",
            [
                "program",
                "requirement_id",
                "label",
                "min_credits",
                "n_of_m",
                "eligible_courses",
            ],
            [r.model_dump() for r in catalog.degree_requirements],
        ),
        (
            "registration_state",
            ["course_id", "term", "available_seats", "total_seats"],
            [r.model_dump() for r in catalog.registration_state],
        ),
        (
            "student_states",
            [
                "student_id",
                "display_name",
                "synthetic",
                "scenario",
                "program",
                "completed_courses",
                "current_term",
                "target_graduation_term",
                "max_term_credits",
                "min_term_credits",
            ],
            [s.model_dump() for s in catalog.student_states],
        ),
    ]

    for table, columns, rows in plan:
        sections.extend(_insert_statements(table, columns, rows))
        sections.append("")

    sections.append("COMMIT;")
    return "\n".join(sections) + "\n"


def export() -> tuple[Path, Path, Catalog]:
    """Write both artifacts and return their paths plus the catalog."""
    catalog = build_catalog()

    # Fail before writing anything if the data cannot form a valid DAG.
    graph = build_graph(catalog)

    SEED_DIR.mkdir(parents=True, exist_ok=True)
    FIXTURE_FILE.write_text(
        json.dumps(catalog.model_dump(), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    SEED_SQL_FILE.write_text(render_seed_sql(catalog), encoding="utf-8")

    nodes, edges = graph_signature(graph)
    print(f"catalog: {len(catalog.courses)} courses, {len(edges)} prerequisite edges")
    print(f"         {len(catalog.degree_requirements)} degree requirements")
    print(f"         {len(catalog.registration_state)} registration rows")
    print(f"         {len(catalog.student_states)} synthetic personas")
    print(f"         graph nodes={len(nodes)} is_dag=True")
    print(f"wrote {FIXTURE_FILE}")
    print(f"wrote {SEED_SQL_FILE}")
    return FIXTURE_FILE, SEED_SQL_FILE, catalog


if __name__ == "__main__":
    export()
